#### GWAS Catalog #####
GWASCat_url: 'https://www.ebi.ac.uk/gwas/api/search/downloads/alternative'
entities_header: 
    - 'ID'
    - 'TYPE'
    - 'title'
    - 'date'
    - 'sample_size'
    - 'replication_size'
    - 'trait'
relationships_header: 
    - 'START_ID'
    - 'END_ID'
    - 'TYPE'
    - 'source'
